on:
  workflow_dispatch:
jobs:
  e2e-tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install
      - run: npx playwright install-deps
      - name: Install dependencies and run tests
        run: npm test
