on:
  workflow_dispatch:
jobs:
  e2e-tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npx --yes playwright@1.19.1 install --with-deps
      - run: npm install
      - run: npm playwright test
