on:
  workflow_dispatch:
jobs:
  e2e-tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install npm@latest -g
      - run: npx playwright install --with-deps
      - run: npm test
